### ISSUE TITLE
Spelling Mistake 

### ISSUE THREAD

**Issue by TechMorgan** [privacytoolslist/privacytoolslist.com#1]
![Screenshot 2021-06-15 at 3 58 35 PM](https://user-images.githubusercontent.com/83485038/122038046-d4bf0400-cdf2-11eb-8e15-78222da84db2.png)

* ### taild > tails
* ### agains > against

**Comment by privacytoolslist** [comment]
@TechMorgan Thank you! Fixed

**Comment by TechMorgan** [comment]
![Screenshot 2021-09-07 at 4 18 31 PM](https://user-images.githubusercontent.com/83485038/132332757-5acbf387-bdeb-4b23-80f1-5ee781065b47.png)

- ###  Another one - recorver > recorder
