### ISSUE TITLE
Add Skiff (Skiff.com)

### ISSUE THREAD

**Issue by amilich** [privacytoolslist/privacytoolslist.com#6]
Hi all! I'm one of the developers of [Skiff](https://skiff.com) - private, end-to-end encrypted email, collaboration, and file storage. Our product code is open source at https://github.com/skiff-org/, and we'd love to be included on `privacytoolslist`.

How can we make this possible?

**Comment by privacytoolslist** [comment]
Hello, the main goal of Skiff is paid service as I see it. Users will not get anything if you provide a link to your sources

**Comment by amilich** [comment]
> Hello, the main goal of Skiff is paid service as I see it. Users will not get anything if you provide a link to your sources

Hi! This isn’t accurate. You get almost all features for free, including 10 GB storage, email, drive, and docs.
